### ISSUE TITLE
Crash when mining Nether Quartz or Glowstone

### ISSUE THREAD

**Issue by Tedyhere** [skyboy/NetherOres#47] opened 2016-01-31 03:47 UTC
Crash report:
---- Minecraft Crash Report ----
// This doesn't make any sense!
Time: 1/30/16 7:45 PM
Description: Ticking entity
java.lang.NullPointerException: Ticking entity
at cpw.mods.fml.common.registry.GameRegistry$UniqueIdentifier.<init>(GameRegistry.java:389)
at cpw.mods.fml.common.registry.GameData.getUniqueName(GameData.java:226)
at cpw.mods.fml.common.registry.GameRegistry.findUniqueIdentifierFor(GameRegistry.java:447)
at me.otho.customItems.mod.handler.BlockDropHandler.onBlockDrop(BlockDropHandler.java:46)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_333_BlockDropHandler_onBlockDrop_HarvestDropsEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:162)
at net.minecraft.block.Block.func_149690_a(Block.java:656)
at net.minecraft.block.BlockOre.func_149690_a(BlockOre.java:54)
at powercrystals.netherores.NetherOresCore$1.func_149690_a(NetherOresCore.java:144)
at net.minecraft.world.Explosion.func_77279_a(Explosion.java:212)
at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:902)
at powercrystals.netherores.entity.EntityArmedOre.explode(EntityArmedOre.java:94)
at powercrystals.netherores.entity.EntityArmedOre.func_70071_h_(EntityArmedOre.java:74)
at net.minecraft.world.World.func_72866_a(World.java:2070)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
at net.minecraft.world.World.func_72870_g(World.java:2034)
at net.minecraft.world.World.func_72939_s(World.java:1887)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Stacktrace:
at cpw.mods.fml.common.registry.GameRegistry$UniqueIdentifier.<init>(GameRegistry.java:389)
at cpw.mods.fml.common.registry.GameData.getUniqueName(GameData.java:226)
at cpw.mods.fml.common.registry.GameRegistry.findUniqueIdentifierFor(GameRegistry.java:447)
at me.otho.customItems.mod.handler.BlockDropHandler.onBlockDrop(BlockDropHandler.java:46)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_333_BlockDropHandler_onBlockDrop_HarvestDropsEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:162)
at net.minecraft.block.Block.func_149690_a(Block.java:656)
at net.minecraft.block.BlockOre.func_149690_a(BlockOre.java:54)
at powercrystals.netherores.NetherOresCore$1.func_149690_a(NetherOresCore.java:144)
at net.minecraft.world.Explosion.func_77279_a(Explosion.java:212)
at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:902)
at powercrystals.netherores.entity.EntityArmedOre.explode(EntityArmedOre.java:94)
at powercrystals.netherores.entity.EntityArmedOre.func_70071_h_(EntityArmedOre.java:74)
at net.minecraft.world.World.func_72866_a(World.java:2070)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
at net.minecraft.world.World.func_72870_g(World.java:2034)
-- Entity being ticked --
Details:
Entity Type: NetherOres.ArmedOre (powercrystals.netherores.entity.EntityArmedOre)
Entity ID: 3233
Entity Name: entity.NetherOres.ArmedOre.name
Entity's Exact location: -282.50, 14.50, 383.50
Entity's Block location: World: (-283,14,383), Chunk: (at 5,0,15 in -18,23; contains blocks -288,0,368 to -273,255,383), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1887)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
-- Affected level --
Details:
Level name: Meatycraft1710
All players: 1 total; [EntityPlayerMP['GGearZZ'/405, l='Meatycraft1710', x=-301.85, y=51.88, z=259.74]]
Chunk stats: ServerChunkCache: 355 Drop: 0
Level seed: 4117430908390750034
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options: 
Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 0 game time, 0 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1210599312 bytes (1154 MB) / 2600468480 bytes (2480 MB) up to 3817865216 bytes (3641 MB)
JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 28, allocated: 1, tallocated: 17
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 122 mods loaded, 122 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
UCHIJAAAA FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10.jar) 
UCHIJAAAA Forge{10.13.4.1566} [Minecraft Forge] (forge-1.7.10-10.13.4.1566-1.7.10.jar) 
UCHIJAAAA appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
UCHIJAAAA Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
UCHIJAAAA CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
UCHIJAAAA NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
UCHIJAAAA OpenModsCore{0.9} [OpenModsCore] (minecraft.jar) 
UCHIJAAAA <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
UCHIJAAAA mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
UCHIJAAAA debug{1.0} [debug] (denseores-1.6.2.jar) 
UCHIJAAAA gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
UCHIJAAAA bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
UCHIJAAAA ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
UCHIJAAAA fusionutil{0.1} [FusionUtil] ([1.7.10]FusionUtil-0.1.0.jar) 
UCHIJAAAA rpgloot{1.0} [RPG Loot] ([1.7.10]RPGLoot-1.0.1.jar) 
UCHIJAAAA StartingInventory{1.7.10.r03} [StartingInventory] ([1.7.10]StartingInventory-universal-1.7.10.r03.jar) 
UCHIJAAAA Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
UCHIJAAAA CoFHCore{1.7.10R3.1.0B1} [CoFH Core] (CoFHCore-[1.7.10]3.1.0B1-322.jar) 
UCHIJAAAA BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
UCHIJAAAA BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
UCHIJAAAA BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
UCHIJAAAA BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
UCHIJAAAA additionalpipes{4.7.0} [Additional Pipes] (additionalpipes-4.7.1.jar) 
UCHIJAAAA aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
UCHIJAAAA appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
UCHIJAAAA Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
UCHIJAAAA AromaBackup{0.0.0.6} [AromaBackup] (AromaBackup-1.7.10-0.0.0.6.jar) 
UCHIJAAAA AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.7.10-0.0.0.6.jar) 
UCHIJAAAA autopackager{1.5.7} [AutoPackager] (autopackager-1.5.7.jar) 
UCHIJAAAA BetterChests{1.1.1.9} [BetterChests] (BetterChests-1.7.10-1.1.1.9.jar) 
UCHIJAAAA betterquesting{1.0.17} [Better Questing] (BetterQuesting-1.0.17.jar) 
UCHIJAAAA BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
UCHIJAAAA Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
UCHIJAAAA Natura{2.2.0} [Natura] (natura-1.7.10-2.2.1a2.jar) 
UCHIJAAAA BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1640-universal.jar) 
UCHIJAAAA MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
UCHIJAAAA ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
UCHIJAAAA BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
UCHIJAAAA BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
UCHIJAAAA Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
UCHIJAAAA Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
UCHIJAAAA ImmersiveEngineering{0.7.1.2} [Immersive Engineering] (ImmersiveEngineering-0.7.1.2.jar) 
UCHIJAAAA Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
UCHIJAAAA TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
UCHIJAAAA boilerplate{6.0.0} [Boilerplate] (boilerplate-1.7.10-6.1.1.52-universal.jar) 
UCHIJAAAA Botania{r1.8-248} [Botania] (Botania r1.8-248.jar) 
UCHIJAAAA BrandonsCore{1.0.0.10} [Brandon's Core] (BrandonsCore-1.0.0.10-bugfix.jar) 
UCHIJAAAA BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
UCHIJAAAA BuildCraft|Compat{7.1.3} [BuildCraft Compat] (buildcraft-compat-7.1.3.jar) 
UCHIJAAAA EvenMoreButtons{0.0.3} [EvenMoreButtons] (Buttons-0.0.3.jar) 
UCHIJAAAA CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
UCHIJAAAA chancecubes{1.7.10-1.6.2.72} [Chance Cubes] (ChanceCubes-1.7.10-1.6.2.72.jar) 
UCHIJAAAA TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
UCHIJAAAA chisel{2.9.4.10} [Chisel] (Chisel-2.9.4.10.jar) 
UCHIJAAAA Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
UCHIJAAAA chiseltones{@VERSION@} [Chisel Tones] (ChiselTones-1.7.10-1.0-3.jar) 
UCHIJAAAA chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
UCHIJAAAA compactstorage{v2.0.0a} [CompactStorage] (compactstorage-1.7.10-release-2.1.0-lts.21-universal.jar) 
UCHIJAAAA customitems{1.0.9b} [Meta Mod: Custom Items] (customitems-1.0.9_beta_1.7.10.jar) 
UCHIJAAAA CustomMainMenu{1.9.2} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.9.2.jar) 
UCHIJAAAA DraconicEvolution{1.0.2-snapshot_9} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2-Snapshot_9.jar) 
UCHIJAAAA eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
UCHIJAAAA endercompass{1.2} [Ender Compass] (EnderCompass-1.7.10-1.2.jar) 
UCHIJAAAA EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
UCHIJAAAA etfuturum{1.5.4} [Et Futurum] (Et Futurum-1.5.4.jar) 
UCHIJAAAA extrabuttons{1.7.10.1} [ExtraButtons] (ExtraButtons-1.7.10.1.jar) 
UCHIJAAAA fognerf{1.7.10-0.3} [Fog Nerf] (fognerf-1.7.10-0.4.jar) 
UCHIJAAAA GlobalGameRules{{}} [Global GameRules] (GlobalGameRules-1.0.jar) 
UCHIJAAAA GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.2.7.jar) 
UCHIJAAAA headcrumbs{1.7.3} [Headcrumbs] (Headcrumbs-1.7.3.jar) 
UCHIJAAAA HoloInventory{1.9.1.123} [HoloInventory] (HoloInventory-1.7.10-1.9.1.123.jar) 
UCHIJAAAA iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
UCHIJAAAA immersiveintegration{0.6.6} [Immersive Integration] (immersiveintegration-0.6.6.jar) 
UCHIJAAAA inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
UCHIJAAAA inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
UCHIJAAAA IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
UCHIJAAAA JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
UCHIJAAAA journeymap{5.1.3} [JourneyMap] (journeymap-1.7.10-5.1.3-unlimited.jar) 
UCHIJAAAA lootbags{1.8.1} [Loot Bags] (LootBags-1.7.10-1.8.1.jar) 
UCHIJAAAA MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAAAA MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
UCHIJAAAA Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.0-1.jar) 
UCHIJAAAA neiintegration{1.1.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.1.jar) 
UCHIJAAAA NetherOres{1.7.10R2.3.1RC1} [Nether Ores] (NetherOres-[1.7.10]2.3.1RC1-19.jar) 
UCHIJAAAA notenoughkeys{@MOD_VERSION@} [NotEnoughKeys] (NotEnoughKeys-1.7.10-3.0.0b45-dev-universal.jar) 
UCHIJAAAA OpenMods{0.9} [OpenMods] (OpenModsLib-1.7.10-0.9.jar) 
UCHIJAAAA OpenBlocks{1.5} [OpenBlocks] (OpenBlocks-1.7.10-1.5.jar) 
UCHIJAAAA pandorasbox{2.0.1} [Pandora's Box] (PandorasBox-2.1.jar) 
UCHIJAAAA PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6.jar) 
UCHIJAAAA recallstones{0.5.2} [Recall Stones] (RecallStones-1.7.10-0.5.2.jar) 
UCHIJAAAA libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
UCHIJAAAA xreliquary{1.2} [Reliquary] (Reliquary-1.2.257.jar) 
UCHIJAAAA ResourceLoader{1.2} [Resource Loader] (ResourceLoader-1.2.jar) 
UCHIJAAAA bq_standard{1.0.11} [Standard Expansion] (StandardExpansion-1.0.11.jar) 
UCHIJAAAA steamcraft2{B5.0.0} [Steamcraft 2] (steamcraft2-1.7.10-B5.0.0.jar) 
UCHIJAAAA StorageDrawers{1.7.10-1.7.7} [Storage Drawers] (StorageDrawers-1.7.10-1.7.7.jar) 
UCHIJAAAA tcinventoryscan{1.0.10} [TC Inventory Scanning] (tcinventoryscan-mc1.7.10-1.0.10.jar) 
UCHIJAAAA thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
UCHIJAAAA TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
UCHIJAAAA transformers{${version}} [Transformers Mod] (Transformers-1.7.10-0.5.10.jar) 
UCHIJAAAA vocation{GRADLE:VERSION-GRADLE:BUILD} [Vocation] (Vocation 1.0-1.jar) 
UCHIJAAAA weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
UCHIJAAAA denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
Class transformer null safety: all safe
CoFHCore: -[1.7.10]3.1.0B1-322
AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
Mantle Environment: Environment healthy.
MineFactoryReloaded: -[1.7.10]2.8.0-104
TConstruct Environment: Environment healthy.
NetherOres: -[1.7.10]2.3.1RC1-19
Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
Stencil buffer state: Function set: GL30, pool: forge, bits: 8
AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Player Count: 1 / 8; [EntityPlayerMP['GGearZZ'/405, l='Meatycraft1710', x=-301.85, y=51.88, z=259.74]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by skyboy** [comment] 2016-01-31 04:19
Duplicate of https://github.com/skyboy/NetherOres/issues/34

**Closed by skyboy** 2016-01-31 04:19 UTC
Labels: duplicate
